### ISSUE TITLE
 Crashes when using

### ISSUE THREAD

**Issue by Leveree** [Mark2Mark/presenter-pro-plugin#4]
When I want to use the plugin, it always crashes directly, the option does not appear in the context menu, and it cannot be purchased.
My Glyphs version is on 3190.

**Comment by Mark2Mark** [comment]
HI @Leveree 

Thanks for the report. Did it happen before? Is the Presenter installed from the Plugin manager?

If yes to both, in the meantime you can use a lower version of Glyphs. It’s very common that newer cutting edge versions of Glyphs break things that some plugins rely on.

**Comment by Leveree** [comment]
This problem has existed since I installed the plugin from the Plugin manager.
May I ask which version is recommended.

**Comment by Leveree** [comment]
> HI @Leveree
> 
> Thanks for the report. Did it happen before? Is the Presenter installed from the Plugin manager?
> 
> If yes to both, in the meantime you can use a lower version of Glyphs. It’s very common that newer cutting edge versions of Glyphs break things that some plugins rely on.

This problem has existed since I installed the plugin from the Plugin manager.
May I ask which version is recommended.

**Comment by Mark2Mark** [comment]
For the moment I recommend this version [https://updates.glyphsapp.com/Glyphs3.1.2-3151.zip](https://updates.glyphsapp.com/Glyphs3.1.2-3151.zip)
This build was very stable and all my plugins work as expected until that point. I still use that for production work at the moment.
_(Note: you can have multiple versions of Glyphs running, as long as you rename them to have different names)_

---

For finding the issue and fixing it:
May I ask when you installed the plugin? As you said "since then", but I don’t know when that was :)
Did you try this with older Glyphs versions?

Thanks for your help @Leveree !

**Comment by Leveree** [comment]
> 

I first install the plugin on 20 March.

The plugin still crashed when I ran the version 3151, then I tried to reinstall it. It showed I install it successfully in the Plugin Manager. However, a little while later, I was told 'Failed to fetch from remote'.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/120783518/235360083-b2b5cfda-96db-47e1-831e-c12e086bf040.png">

**Comment by Leveree** [comment]
> For the moment I recommend this version https://updates.glyphsapp.com/Glyphs3.1.2-3151.zip This build was very stable and all my plugins work as expected until that point. I still use that for production work at the moment. _(Note: you can have multiple versions of Glyphs running, as long as you rename them to have different names)_
> 
> For finding the issue and fixing it: May I ask when you installed the plugin? As you said "since then", but I don’t know when that was :) Did you try this with older Glyphs versions?
> 
> Thanks for your help @Leveree !

I first install the plugin on 20 March.

The plugin still crashed when I ran the version 3151, then I tried to reinstall it. It showed I install it successfully in the Plugin Manager. However, a little while later, I was told 'Failed to fetch from remote'.
![image](https://user-images.githubusercontent.com/120783518/235360198-c58ba7db-d7e0-4d72-8f1e-2ee1a4491c27.png)

**Comment by Leveree** [comment]
> For the moment I recommend this version https://updates.glyphsapp.com/Glyphs3.1.2-3151.zip This build was very stable and all my plugins work as expected until that point. I still use that for production work at the moment. _(Note: you can have multiple versions of Glyphs running, as long as you rename them to have different names)_
> 
> For finding the issue and fixing it: May I ask when you installed the plugin? As you said "since then", but I don’t know when that was :) Did you try this with older Glyphs versions?
> 
> Thanks for your help @Leveree !

It seems that I haven't install it successfully, if I installed other plugins successfully then I'll be asked to restart Glyphs app. Presenter only showed the Remove button in the Plugin Manager, didn't ask for restarting the App.

**Comment by Mark2Mark** [comment]
May I ask if you're located in China? The plugin needs to call the shop system occasionally, which has its servers in the US and perhaps in GB. It could be that in China the access is blocked. Do you have a VPN by any chance? With that you could bypass such blocking perhaps. 

Sorry for the inconvenience!

Did you ever try any of my other paid plugins? If any of those work, than we can exclude this blocking scenario. Otherwise if those also fail to work, we would have pinned the problem.
